### ISSUE TITLE
Nodejsscan failing : Attaching logs

### ISSUE THREAD

**Issue by FebiDev** [ajinabraham/nodejsscan#206]
Hello,

When I run nodejsscan in my project I am getting the below error, the same scan worked perfectly fine mid of November 2020 and I was able to get the report also. It is failing  recently,

Could you please help in resolving the issue or any recommendations.

$ /analyzer run
[INFO] [NodeJsScan] [2020-12-08T09:46:05Z] ▶ GitLab NodeJsScan analyzer v2.12.0
[INFO] [NodeJsScan] [2020-12-08T09:46:05Z] ▶ Detecting project
[INFO] [NodeJsScan] [2020-12-08T09:46:05Z] ▶ Found project in /builds/gts/g
[INFO] [NodeJsScan] [2020-12-08T09:46:05Z] ▶ Running analyzer
[DEBU] [NodeJsScan] [2020-12-08T09:46:05Z] ▶ /builds/gts/g/.gitlab/sast-ruleset.toml not found, ruleset support will be disabled.
[DEBU] [NodeJsScan] [2020-12-08T09:53:44Z] ▶ /usr/local/bin/njsscan --json --output /tmp/njsscan.json /builds/gts/g
Traceback (most recent call last):
  File "/usr/local/bin/njsscan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/njsscan/__main__.py", line 69, in main
    args.missing_controls,
  File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 37, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 42, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 230, in main
    ).invoke_semgrep(target_manager, all_rules)
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 532, in invoke_semgrep
    rules, target_manager
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 500, in _run_rules
    rule, target_manager, semgrep_core_ast_cache_dir, max_timeout_files
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 425, in _run_rule
    rule, pattern_matches, self._allow_exec
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 366, in evaluate
    steps_for_debugging=steps_for_debugging,
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 427, in evaluate_expression
    flags=flags,
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 468, in _evaluate_expression
    flags=flags,
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 489, in _evaluate_expression
    flags=flags,
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 261, in _evaluate_single_expression
    list(flatten(pattern_ids_to_pattern_matches.values())),
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 50, in get_re_range_matches
    for pm in pattern_matches
  File "/usr/local/lib/python3.7/site-packages/semgrep/evaluation.py", line 50, in <genexpr>
    for pm in pattern_matches
  File "/usr/local/lib/python3.7/site-packages/semgrep/pattern_match.py", line 80, in get_metavariable_value
    value = file.read(length)
  File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 2371: invalid start byte
[FATA] [NodeJsScan] [2020-12-08T09:53:44Z] ▶ open /tmp/njsscan.json: no such file or directory
Uploading artifacts for failed job

Thanks in advance

**Comment by ajinabraham** [comment]
` GitLab NodeJsScan analyzer v2.12.0` is not maintained by us. Please reach out to https://gitlab.com/gitlab-org/security-products/analyzers/nodejs-scan/ 

Also, ensure that `njsscan` is the latest.

**Comment by FebiDev** [comment]
Thanks for your inputs...
