### ISSUE TITLE
Exception on /upload/

### ISSUE THREAD

**Issue by antisec135** [ajinabraham/nodejsscan#207]
I got his when I tried uploading a zip file, I used the latest docker image:

Exception on /upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 314, in _parse_core_output
    return cast(Dict[str, Any], json.loads(semgrep_output))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/nodejsscan/nodejsscan/app.py", line 89, in upload
    return handle_upload(app, request)
  File "/usr/src/nodejsscan/web/upload.py", line 85, in handle_upload
    results = nodejsscan.scan(app_dir)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 71, in scan
    result = call_njsscan(node_source)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 50, in call_njsscan
    return scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/njsscan/njsscan.py", line 37, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/helpers.py", line 44, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/semgrep_main.py", line 251, in main
    target_manager, filtered_rules
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 556, in invoke_semgrep
    rules, target_manager, profiler
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 520, in _run_rules
    profiler,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 415, in _run_rule
    cache_dir,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 297, in _run_core_command
    output_json = self._parse_core_output(core_run.stdout)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 317, in _parse_core_output
    f"unexpected non-json output while invoking semgrep-core:\n{semgrep_output}\n\n{PLEASE_FILE_ISSUE_TEXT}"
semgrep.error.SemgrepError: unexpected non-json output while invoking semgrep-core:

An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

**Comment by ajinabraham** [comment]
This is probably a semgrep exception. Can you isolate the problematic file or share the zip that can reproduce this issue?

**Comment by ajinabraham** [comment]
No response

**Comment by anacoimbrag** [comment]
Hello guys! I'm having the same issue here. My stacktrace:

Traceback (most recent call last):
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/nodejsscan/app.py", line 89, in upload
    return handle_upload(app, request)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/web/upload.py", line 85, in handle_upload
    results = nodejsscan.scan(app_dir)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/nodejsscan/nodejsscan.py", line 71, in scan
    result = call_njsscan(node_source)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/nodejsscan/nodejsscan.py", line 50, in call_njsscan
    return scanner.scan()
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/njsscan/njsscan.py", line 37, in scan
    result = scanner.scan()
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/libsast/scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/libsast/core_sgrep/helpers.py", line 35, in invoke_semgrep
    semgrep_main.main(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 242, in main
    ) = CoreRunner(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/core_runner.py", line 549, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, all_targets = self._run_rules(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/core_runner.py", line 509, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/core_runner.py", line 406, in _run_rule
    output_json = profiler.track(
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/core_runner.py", line 292, in _run_core_command
    core_run = sub_run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/util.py", line 136, in sub_run
    result = subprocess.run(cmd, **kwargs)  # nosem: python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/anacoimbra/Documents/GitHub/nodejsscan/venv/lib/python3.8/site-packages/semgrep/bin/semgrep-core'

**Comment by ajinabraham** [comment]
Hi @anacoimbrag Can you share your OS version and architecture.

Please ensure that you are on the latest version of nodejsscan.

Also please share the output of 
```
source venv/bin/activate
semgrep --version
```

**Comment by ajinabraham** [comment]
Are you on an apple M1 ARM-based mac? semgrep is not targeted for ARM and will not work natively.

**Comment by sridharan377** [comment]
i am also facing a same issues
