### ISSUE TITLE
Hangs on upload

### ISSUE THREAD

**Issue by xplo8** [ajinabraham/nodejsscan#225]
** ************ pulled a fresh docker image using *******

╰─ docker pull opensecurity/nodejsscan:latest
latest: Pulling from opensecurity/nodejsscan
Digest: sha256:908411387263cdcf3f63b0372f1cfc0c11594c980e8a38f3dcc986d2751de5ce
Status: Image is up to date for opensecurity/nodejsscan:latest
docker.io/opensecurity/nodejsscan:latest
 
************* running the image as directed ****

╰─ docker run -it -p 9090:9090 opensecurity/nodejsscan:latest

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-05-17 22:25:57.060 UTC [49] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-05-17 22:25:57.062 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-05-17 22:25:57.076 UTC [50] LOG:  database system was shut down at 2021-05-17 22:25:56 UTC
2021-05-17 22:25:57.081 UTC [49] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-05-17 22:25:57.304 UTC [49] LOG:  received fast shutdown request
waiting for server to shut down....2021-05-17 22:25:57.306 UTC [49] LOG:  aborting any active transactions
2021-05-17 22:25:57.307 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
2021-05-17 22:25:57.309 UTC [51] LOG:  shutting down
2021-05-17 22:25:57.321 UTC [49] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-05-17 22:25:57.426 UTC [7] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-05-17 22:25:57.427 UTC [7] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-05-17 22:25:57.427 UTC [7] LOG:  listening on IPv6 address "::", port 5432
2021-05-17 22:25:57.431 UTC [7] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-05-17 22:25:57.449 UTC [67] LOG:  database system was shut down at 2021-05-17 22:25:57 UTC
2021-05-17 22:25:57.454 UTC [7] LOG:  database system is ready to accept connections
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from flask_script import Manager
  File "/usr/local/lib/python3.7/dist-packages/flask_script/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'
[2021-05-17 22:26:06 +0000] [77] [INFO] Starting gunicorn 20.1.0
[2021-05-17 22:26:06 +0000] [77] [INFO] Listening at: http://0.0.0.0:9090 (77)
[2021-05-17 22:26:06 +0000] [77] [INFO] Using worker: gthread
[2021-05-17 22:26:06 +0000] [80] [INFO] Booting worker with pid: 80
2021-05-17 22:26:34.383 UTC [89] ERROR:  relation "nodejsscan_results" does not exist at character 623
2021-05-17 22:26:34.383 UTC [89] STATEMENT:  SELECT nodejsscan_results.id AS nodejsscan_results_id, nodejsscan_results.scan_file AS nodejsscan_results_scan_file, nodejsscan_results.scan_hash AS nodejsscan_results_scan_hash, nodejsscan_results.location AS nodejsscan_results_location, nodejsscan_results.nodejs AS nodejsscan_results_nodejs, nodejsscan_results.templates AS nodejsscan_results_templates, nodejsscan_results.files AS nodejsscan_results_files, nodejsscan_results.false_positive AS nodejsscan_results_false_positive, nodejsscan_results.not_applicable AS nodejsscan_results_not_applicable, nodejsscan_results.timestamp AS nodejsscan_results_timestamp
	FROM nodejsscan_results
	WHERE nodejsscan_results.scan_hash = 'c1e08ae7f1fb4b7019f8662776fdf5bc77420c74fd15d64196c3113cce40b2ef'
	 LIMIT 1
Exception on /upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "nodejsscan_results" does not exist
LINE 2: FROM nodejsscan_results
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/src/nodejsscan/nodejsscan/app.py", line 89, in upload
    return handle_upload(app, request)
  File "/usr/src/nodejsscan/web/upload.py", line 72, in handle_upload
    if is_scan_exists(sha2):
  File "/usr/src/nodejsscan/web/db_operations.py", line 72, in is_scan_exists
    return ScanResults.query.filter(ScanResults.scan_hash == sha256).first()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 2750, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 2837, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 330, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "nodejsscan_results" does not exist
LINE 2: FROM nodejsscan_results
             ^

[SQL: SELECT nodejsscan_results.id AS nodejsscan_results_id, nodejsscan_results.scan_file AS nodejsscan_results_scan_file, nodejsscan_results.scan_hash AS nodejsscan_results_scan_hash, nodejsscan_results.location AS nodejsscan_results_location, nodejsscan_results.nodejs AS nodejsscan_results_nodejs, nodejsscan_results.templates AS nodejsscan_results_templates, nodejsscan_results.files AS nodejsscan_results_files, nodejsscan_results.false_positive AS nodejsscan_results_false_positive, nodejsscan_results.not_applicable AS nodejsscan_results_not_applicable, nodejsscan_results.timestamp AS nodejsscan_results_timestamp
FROM nodejsscan_results
WHERE nodejsscan_results.scan_hash = %(scan_hash_1)s
 LIMIT %(param_1)s]
[parameters: {'scan_hash_1': 'c1e08ae7f1fb4b7019f8662776fdf5bc77420c74fd15d64196c3113cce40b2ef', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/14/f405)

****************** hangs while analyzing ***************************************

![image](https://user-images.githubusercontent.com/15901952/118564233-cfec2f00-b724-11eb-8df5-67522679db16.png)

**Comment by ajinabraham** [comment]
Thanks for reporting. The latest Flask broke some dependencies. This should be fixed in the latest master. Please pull the latest docker image once it's built.

**Comment by ajinabraham** [comment]
closing this as the latest image works. Feel free to comment if it's not working for you.
