### ISSUE TITLE
Bug: Crash on what appears to be empty file

### ISSUE THREAD

**Issue by davewichers** [ajinabraham/nodejsscan#234]
I have a private NodeJS app I'm working on, and I zipped up the entire directory and dropped it into the Web UI of the NodeJSScan displayed by the Docker image. I have the full stack trace at the bottom.

I believe there are at least 2, possibly 3 issues here:

1) The error was displayed in the console below, but never propagated to the web UI. I just saw the 'Analyzing....' (1 dot thru 4 dots repeating forever).  It took like 1 minute (or less) for the error message below to appear in the console.

So, can you fix the WebUI to detect when errors occur and propagate something to the user so they know the scan has already stopped/failed?

2) I'm not sure if the error is in NodeJSScan itself and/or SemGrep.

Based on the error message: "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

It seems like SemGrep can't handle empty files. If that is true then I have 2 ideas to help fix this:

2a) Have NodeJSScan itself check the file size and if 0, don't pass it to SemGrep. If SemGrep is expecting specific types of files only, then maybe filter the files passed to it, so it only get's the file types it expects.

2b) Report this error to the SemGrep team directly as well, as it seems like SemGrep should be able to gracefully handle/skip file types/content sizes it doesn't like, rather than just crashing.  Seems like issuing a warning, with the path/name of file would be far better than halting like this.

Here is the console output from the Docker image:

[INFO] Unzipping file
[INFO] Performing Static Analysis
Exception on /upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 319, in _parse_core_output
    return cast(Dict[str, Any], json.loads(semgrep_output))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/src/nodejsscan/nodejsscan/app.py", line 89, in upload
    return handle_upload(app, request)
  File "/usr/src/nodejsscan/web/upload.py", line 85, in handle_upload
    results = nodejsscan.scan(app_dir)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 71, in scan
    result = call_njsscan(node_source)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 50, in call_njsscan
    return scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/njsscan/njsscan.py", line 43, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/helpers.py", line 44, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/semgrep_main.py", line 263, in main
    target_manager, profiler, filtered_rules, optimizations
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 744, in invoke_semgrep
    ) = runner_fxn(rules, target_manager, profiler)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 582, in _run_rules
    profiling_data,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 478, in _run_rule
    cache_dir,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 263, in _run_core_command
    output_json = self._extract_core_output(rule, patterns, core_run)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 289, in _extract_core_output
    rule, core_run, semgrep_output, semgrep_error_output, returncode
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 327, in _parse_core_output
    semgrep_error_output,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 344, in _fail
    f"semgrep-core failed: {reason}\n"
semgrep.error.SemgrepError: semgrep-core failed: unparseable json output
rule ID: 'usr.local.lib.python3.7.dist-packages.njsscan.rules.semantic_grep.electronjs.electron_disable_websecurity'
semgrep-core exit code: -11
semgrep-core command: /usr/local/lib/python3.7/dist-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmpdfz9hntr -j 8 -target_file /tmp/tmpewkcuh5v -use_parsing_cache /tmp/tmpfeg4d25l -timeout 5 -max_memory 0
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

**Comment by ajinabraham** [comment]
Hi @davewichers 

I am assuming that you are using the latest version of nodejsscan (`v4.5` as of now). If not, please test again on the latest release. We normally have a pass to ignore binary and other non js files before passing it to semgrep.
Can you provide a sample zip that can replicate the issue. (obviously remove the source code, but include the relevant bits of file(s) that causes the exception)?

**Comment by davewichers** [comment]
I'm running it like so:
docker pull opensecurity/nodejsscan:latest
docker run -it -p 9090:9090 opensecurity/nodejsscan:latest

So, yes, the latest. :-)

I actually just found the command line version of your tool, so I'm starting to use that.  As to which file caused the problem, I'm not sure. Seems like the error handling for the above should also spit out the name of the file where the problem occurred. Can you enhance your web app to do that too?

**Comment by ajinabraham** [comment]
The exception happens inside semgrep-core. So we don't have access to the information on which file caused the issue. May be consider opening an issue upstream with semgrep. They will still require a sample set to reproduce this issue I believe.
