### ISSUE TITLE
Getting json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Kladizkov** [ajinabraham/nodejsscan#241]
When I try to do the scan on nodejs app, I get this error.

How can I fix it?

```
[2021-09-23 05:27:29 +0000] [80] [INFO] Starting gunicorn 20.1.0
[2021-09-23 05:27:29 +0000] [80] [INFO] Listening at: http://0.0.0.0:9090 (80)
[2021-09-23 05:27:29 +0000] [80] [INFO] Using worker: gthread
[2021-09-23 05:27:29 +0000] [83] [INFO] Booting worker with pid: 83
[INFO] Unzipping file
[INFO] Performing Static Analysis
Exception on /upload/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 319, in _parse_core_output
    return cast(Dict[str, Any], json.loads(semgrep_output))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/src/nodejsscan/nodejsscan/app.py", line 89, in upload
    return handle_upload(app, request)
  File "/usr/src/nodejsscan/web/upload.py", line 85, in handle_upload
    results = nodejsscan.scan(app_dir)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 71, in scan
    result = call_njsscan(node_source)
  File "/usr/src/nodejsscan/nodejsscan/nodejsscan.py", line 50, in call_njsscan
    return scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/njsscan/njsscan.py", line 43, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/dist-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/usr/local/lib/python3.7/dist-packages/libsast/core_sgrep/helpers.py", line 44, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/semgrep_main.py", line 263, in main
    target_manager, profiler, filtered_rules, optimizations
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 744, in invoke_semgrep
    ) = runner_fxn(rules, target_manager, profiler)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 582, in _run_rules
    profiling_data,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 478, in _run_rule
    cache_dir,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 263, in _run_core_command
    output_json = self._extract_core_output(rule, patterns, core_run)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 289, in _extract_core_output
    rule, core_run, semgrep_output, semgrep_error_output, returncode
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 327, in _parse_core_output
    semgrep_error_output,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 344, in _fail
    f"semgrep-core failed: {reason}\n"
semgrep.error.SemgrepError: semgrep-core failed: unparseable json output
rule ID: 'usr.local.lib.python3.7.dist-packages.njsscan.rules.semantic_grep.headers.cookie_session_no_secure'
semgrep-core exit code: -11
semgrep-core command: /usr/local/lib/python3.7/dist-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmppjdwc7d1 -j 4 -target_file /tmp/tmpa7e7jts7 -use_parsing_cache /tmp/tmp5dw8xpfw -timeout 5 -max_memory 0
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

**Comment by ajinabraham** [comment]
Semgrep bug, please report upstream
