### ISSUE TITLE
module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

### ISSUE THREAD

**Issue by DimitrisMpanis** [ajinabraham/nodejsscan#290]
Trying to install in macos 13.1 with python 3.10.10

when Calling python3 manage.py recreate-db i get the following error:

Traceback (most recent call last):
  File "/Users/dimitrismpanis/Desktop/bugtown/nodejsscan/manage.py", line 6, in <module>
    from nodejsscan.app import (
  File "/Users/dimitrismpanis/Desktop/bugtown/nodejsscan/nodejsscan/app.py", line 9, in <module>
    from nodejsscan.models import db
  File "/Users/dimitrismpanis/Desktop/bugtown/nodejsscan/nodejsscan/models.py", line 8, in <module>
    db = SQLAlchemy()
  File "/Users/dimitrismpanis/Desktop/bugtown/nodejsscan/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/Users/dimitrismpanis/Desktop/bugtown/nodejsscan/venv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

Any ideas?

Thanks

**Comment by ajinabraham** [comment]
Looks like you have wrong versions of the packages installed. Are you installing nodejsscan inside a  python virtualenv?

The error suggests you have a wrong version of sqlalchemy installed. See: https://stackoverflow.com/questions/75275563/attributeerror-module-sqlalchemy-has-no-attribute-all

**Comment by fenugeek** [comment]
Flask-SQLAlchemy (v2.5.1) lets itself be dependent on sqlalchemy 2.0 - which doesn't have __all__ - so requirements.txt needs to now  pin the version of sqlalchemy manually.

Add this line to your requirements.txt:

**SQLAlchemy~=1.4.0**


and re-run `pip install -r requirements.txt`
